export const TESTS_HAS_ERRORED = "TESTS_HAS_ERRORED";
export const TESTS_IS_LOADING = "TESTS_IS_LOADING";
export const TESTS_FETCH_DATA_SUCCESS = "TESTS_FETCH_DATA_SUCCESS";

export const TEST_START = "TEST_START";
export const QUESTION_SET = "QUESTION_SET";

export const ANSWERS_COUNT_INCREMENT = "ANSWERS_COUNT_INCREMENT";
export const SCORE_INCREMENT = "SCORE_INCREMENT";