export const GAMES_HAS_ERRORED = "GAMES_HAS_ERRORED";
export const GAMES_IS_LOADING = "GAMES_IS_LOADING";
export const GAMES_FETCH_DATA_SUCCESS = "GAMES_FETCH_DATA_SUCCESS";

export const GAME_START = "GAME_START";
export const GAME_HAS_ERRORED = "GAME_HAS_ERRORED";
export const GAME_IS_LOADING = "GAME_IS_LOADING";
export const GAME_FETCH_DATA_SUCCESS = "GAME_FETCH_DATA_SUCCESS";
export const GAME_STARTED = "GAME_STARTED";
export const GAME_FINISHED = "GAME_FINISHED";

///////
export const QUESTION_SET = "QUESTION_SET";

export const ANSWERS_COUNT_INCREMENT = "ANSWERS_COUNT_INCREMENT";
export const SCORE_INCREMENT = "SCORE_INCREMENT";
